name: ci-terraform

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci-terraform.yml"
      - "terraform/**"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::010526276358:role/paradise-cakes-api-development-terraform-deployer
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.3.6

      - name: Terraform Init - DEV
        id: tf-init-dev
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform init \
            --backend-config="bucket=paradise-cakes-dev-tfstate" \
            --backend-config="key=paradise-cakes-dev.tfstate"

      - name: Terraform Plan - DEV
        id: tf-plan-dev
        env:
          TF_VAR_environment: "dev"
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform plan --out tfplan.out

      - name: Terraform Apply - DEV
        id: tf-apply-dev
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform apply -auto-approve tfplan.out

  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::132899756990:role/paradise-cakes-api-terraform-deployer
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.3.6

      - name: Terraform Init - PROD
        id: tf-init-prod
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform init -backend-config="key=paradise-cakes.tfstate"

      - name: Terraform Plan - PROD
        id: tf-plan-prod
        env:
          TF_VAR_environment: "prod"
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform plan --out tfplan.out

      - name: Terraform Apply - PROD
        id: tf-apply-prod
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform apply -auto-approve tfplan.out
