name: ci-terraform

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci-terraform.yml"
      - "terraform/**"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::132899756990:role/paradise-cakes-api-terraform-deployer
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: tf-init
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform init -backend-config="key=paradise-cakes.tfstate"

      - name: Terraform Plan
        id: tf-plan
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform plan --out tfplan.out

      - name: Terraform Apply
        id: tf-apply
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform apply -auto-approve tfplan.out
